### ISSUE TITLE
Homebridge Soundtouch Error: connect EHOSTUNREACH

### ISSUE THREAD

**Issue by DutchDeffy** [CONNCTED/homebridge-soundtouch#10]
Dear CONNCTED,

First of all, thanks for the hard work you did and the time you spend on this project. Everything used to work well, until the last few months. Because now when I run homebridge in debug mode using `DEBUG=* homebridge` I get an error: 
```
Got** error: connect EHOSTUNREACH _myi.pad.res.s_2:8090
/usr/local/lib/node_modules/homebridge-soundtouch/node_modules/soundtouch/api.js:353
            throw new Error(e.message);
            ^

Error: connect EHOSTUNREACH _myi.pad.res.s_2:8090
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-soundtouch/node_modules/soundtouch/api.js:353:19)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1255:8)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)
```

Extra information: _myipadress_ is hidden but it just shows the ip adress of the Bose Speaker+ the port

Everything looks to work fine until I open the homekit app or ask Siri to turn on my speaker. I saw a post which said that this was caused because the plugin is outdated. If this is the case I, with this, ask someone on internet to please update this amazing plugin. 

Yours faithfully, 
DutchDefffy

**NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:NL:**
Geachte CNNECTED,

Allereerst bedankt voor het harde werk en de tijd die u aan dit project heeft gespendeerd. Alles werkte geweldig goed, totaan de laatste paar maanden. Want nu als ik homebridge in debug mode run gebruikmakend van het commando `DEBUG=* homebridge` Krijg ik de foutmelding: 
```
Got** error: connect EHOSTUNREACH _myi.pad.res.s_2:8090
/usr/local/lib/node_modules/homebridge-soundtouch/node_modules/soundtouch/api.js:353
            throw new Error(e.message);
            ^

Error: connect EHOSTUNREACH _myi.pad.res.s_2:8090
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-soundtouch/node_modules/soundtouch/api.js:353:19)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1255:8)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)
```
Toevoeging _myipadress_ is veranderd omdat dat gewoon het ip adress van de Bose Speaker is + de poort.

Alles ziet er goed werkend uit totdat u=ik dehomekit app open of siri vraag mijn speaker aan te zetten, dan krijg ik de bovenstaande foutmelding. Ik zag een issue die zei dat dit werd veroorzaakt doordat de plugin verouderd is. Als dit het geval is, vraag ik hierbij iemand op internet om deze geweldige plugin bij te werken. 

Met vriendelijke groet,

DutchDeffy

**Comment by DutchDeffy** [comment]
@geertsmichael ??
