### ISSUE TITLE
Soundtouch plugin preventing Homebridge from starting

### ISSUE THREAD

**Issue by blloyd78** [CONNCTED/homebridge-soundtouch#21]
I recently upgraded the nodejs instance on my Raspberry Pi and the soundtouch plugins no longer work. I receive the following error on start-up:

```
/usr/local/lib/node_modules/homebridge/lib/api.js:64
homebridge_1  |       throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
homebridge_1  |             ^
homebridge_1  | Error: The requested accessory 'SoundTouch' was not registered by any plugin.
```
A dig through the logs shows:

```
[2018-3-23 16:13:55] ERROR LOADING PLUGIN homebridge-soundtouch:
homebridge_1  | [2018-3-23 16:13:55] Error: Cannot find module '../build/Release/dns_sd_bindings'
homebridge_1  |     at Function.Module._resolveFilename (module.js:547:15)
homebridge_1  |     at Function.Module._load (module.js:474:25)
homebridge_1  |     at Module.require (module.js:596:17)
homebridge_1  |     at require (internal/module.js:11:18)
homebridge_1  |     at Object.<anonymous> (/homebridge/node_modules/mdns/lib/dns_sd.js:32:22)
homebridge_1  |     at Module._compile (module.js:652:30)
homebridge_1  |     at Object.Module._extensions..js (module.js:663:10)
homebridge_1  |     at Module.load (module.js:565:32)
homebridge_1  |     at tryModuleLoad (module.js:505:12)
homebridge_1  |     at Function.Module._load (module.js:497:3)
homebridge_1  |     at Module.require (module.js:596:17)
homebridge_1  |     at require (internal/module.js:11:18)
homebridge_1  |     at Object.<anonymous> (/homebridge/node_modules/mdns/lib/mdns.js:1:77)
homebridge_1  |     at Module._compile (module.js:652:30)
homebridge_1  |     at Object.Module._extensions..js (module.js:663:10)
homebridge_1  |     at Module.load (module.js:565:32)
```
Note. This is a pre-built Docker container running a Homebridge instance if that makes any difference.

**Comment by Ghost108** [comment]
Same probleme on a Synology NAS
