### ISSUE TITLE
This plugin on Synology NAS

### ISSUE THREAD

**Issue by Ghost108** [CONNCTED/homebridge-soundtouch#22]
Hey :)

I installed homebridge on my Synology DS718+ with this tutorial: https://github.com/oznu/homebridge-syno-spk#how-to-install

Now I would like to use the soundtouch plugin - installation was successfully.
I updated my config file like this:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "xxx",
        "port": xxx,
        "pin": "xxx"
    },
    "accessories": [
        {
            "accessory": "SoundTouch",
            "name": "Speaker Bathroom",
            "room": "Bathroom"
        }
    ]
}
```

Now I restart my homebridge and the logfile shows this:

> [2018-4-12 21:15:55] [Speaker Bathroom] Initializing SoundTouch accessory...
> Started Searching...
> 
> /homebridge/node_modules/mdns/lib/resolver_sequence_tasks.js:199
>   var e = new Error(syscall + ' ' + errorno);
>           ^
> Error: getaddrinfo -3008
>     at errnoException (/homebridge/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
>     at getaddrinfo_complete (/homebridge/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
>     at GetAddrInfoReqWrap.oncomplete (/homebridge/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)

What does this mean? How can I fix it?

**Comment by ajax3712** [comment]
I can confirm this is happening using this plugin with https://github.com/oznu/docker-homebridge

```
/homebridge/node_modules/mdns/lib/resolver_sequence_tasks.js:199
var e = new Error(syscall + ' ' + errorno);

^
Error: getaddrinfo -3008

at errnoException (/homebridge/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
at getaddrinfo_complete (/homebridge/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
at GetAddrInfoReqWrap.oncomplete (/homebridge/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
```

**Comment by Ghost108** [comment]
and what is the solution ?

**Comment by jwl17330536** [comment]
I'm seeing this too.

**Comment by jvgitrepo** [comment]
Has anyone got an update to this - I have the same issue when trying to add any Accessories?

**Comment by monsterciattolo** [comment]
i'm in this condition too with same docker oznu/docker-homebridge
